"""Markdown report generator — produces engaging, readable reports from analysis."""

from datetime import datetime

from utils import log, save_report


# ──────────────────────────────────────────────
# Title Variations (avoids repetitive titles)
# ──────────────────────────────────────────────

_TITLE_TEMPLATES = [
    "📊 Moltbook Pulse — {date}",
    "🦞 Agent Network Report — {date}",
    "📈 What Agents Are Talking About — {date}",
    "🔬 Moltbook Intelligence Brief — {date}",
    "🌊 Trend Radar — {date}",
    "📡 Agent Ecosystem Scan — {date}",
    "🧠 Moltbook Insights — {date}",
]


def _pick_title(now: datetime) -> str:
    """Pick a varied title based on time."""
    idx = (now.hour + now.day) % len(_TITLE_TEMPLATES)
    return _TITLE_TEMPLATES[idx].format(date=now.strftime("%b %d, %H:%M UTC"))


def _sentiment_emoji(pct: float) -> str:
    if pct >= 20:
        return "🟢"
    elif pct >= 10:
        return "🟡"
    else:
        return "🔴"


def _trend_bar(pct: float) -> str:
    """Visual bar for percentages."""
    filled = round(pct / 10)
    return "█" * filled + "░" * (10 - filled)


def generate_daily_report(analysis: dict, sentiment: dict) -> str:
    """Generate a comprehensive daily report in Markdown."""
    log.info("📝 Generating daily report...")
    now = datetime.now()

    lines = [
        f"# 🦞 Moltbook Ecosystem Report — {now.strftime('%d %B %Y, %H:%M UTC')}",
        "",
        f"> Auto-generated by MoltBridge Agent | Analyzed: {analysis.get('total_unique_posts', 0)} posts from {analysis.get('agent_patterns', {}).get('unique_agents', '?')} agents",
        "",
        "---",
        "",
    ]

    # Top Keywords
    lines.append("## 📈 Trending Topics")
    lines.append("")
    keywords = analysis.get("keywords", [])[:10]
    for i, kw in enumerate(keywords, 1):
        bar = _trend_bar(kw['frequency'] * 100 * 5)
        lines.append(f"{i}. **{kw['keyword']}** — {kw['count']} mentions {bar}")
    lines.append("")

    # Bigram Topics
    bigrams = analysis.get("bigram_topics", [])[:8]
    if bigrams:
        lines.append("## 🔗 Hot Phrases")
        lines.append("")
        for bg in bigrams:
            lines.append(f"- **{bg['topic']}** ({bg['count']}x)")
        lines.append("")

    # Submolt Activity
    submolts = analysis.get("submolt_activity", [])[:6]
    if submolts:
        lines.append("## 🏘️ Most Active Submolts")
        lines.append("")
        lines.append("| Submolt | Posts | Upvotes | Comments | Engagement |")
        lines.append("|---------|-------|---------|----------|------------|")
        for s in submolts:
            lines.append(
                f"| m/{s['submolt']} | {s['post_count']} | "
                f"{s['total_upvotes']} | {s['total_comments']} | "
                f"{s['engagement_score']} |"
            )
        lines.append("")

    # Sentiment
    lines.append("## 💭 Sentiment Analysis")
    lines.append("")
    pcts = sentiment.get("percentages", {})
    pos = pcts.get('positive', 0)
    neu = pcts.get('neutral', 0)
    neg = pcts.get('negative', 0)
    lines.append(f"- {_sentiment_emoji(pos)} Positive: **{pos}%** {_trend_bar(pos)}")
    lines.append(f"- ⚪ Neutral: **{neu}%** {_trend_bar(neu)}")
    lines.append(f"- {_sentiment_emoji(100-neg)} Negative: **{neg}%** {_trend_bar(neg)}")
    lines.append("")

    # Sentiment keywords
    pos_kws = sentiment.get("positive_keywords", [])[:5]
    neg_kws = sentiment.get("negative_keywords", [])[:5]
    if pos_kws or neg_kws:
        if pos_kws:
            pw = ", ".join(f"{pk['word']}({pk['count']})" for pk in pos_kws)
            lines.append(f"Positive signals: {pw}")
        if neg_kws:
            nw = ", ".join(f"{nk['word']}({nk['count']})" for nk in neg_kws)
            lines.append(f"Negative signals: {nw}")
        lines.append("")

    # Trend Changes
    changes = analysis.get("trend_changes", [])
    if changes:
        lines.append("## 🌊 Trend Shifts (vs Previous Period)")
        lines.append("")
        rising = [c for c in changes if "rising" in c["trend"] or "new" in c["trend"]][:5]
        falling = [c for c in changes if "falling" in c["trend"]][:3]

        if rising:
            for r in rising:
                lines.append(f"- {r['trend']} **{r['keyword']}** (+{r['change_pct']}%)")
        if falling:
            for f_item in falling:
                lines.append(f"- {f_item['trend']} **{f_item['keyword']}** ({f_item['change_pct']}%)")
        lines.append("")

    # Agent Patterns
    patterns = analysis.get("agent_patterns", {})
    if patterns:
        lines.append("## 🤖 Agent Activity")
        lines.append("")
        lines.append(f"- Unique agents: **{patterns.get('unique_agents', 0)}**")
        lines.append(f"- Highly active (3+ posts): **{patterns.get('prolific_agents', 0)}**")
        lines.append(f"- One-time posters: **{patterns.get('one_time_posters', 0)}**")
        lines.append("")

        top_posters = patterns.get("top_posters", [])[:5]
        if top_posters:
            lines.append("**Most active agents:**")
            for tp in top_posters:
                lines.append(f"- @{tp['name']} — {tp['posts']} posts, {tp['upvotes']} upvotes")
            lines.append("")

    # Footer
    lines.extend([
        "---",
        "",
        "*Auto-generated by MoltBridge Agent — bridging Moltbook intelligence to the agent ecosystem.*",
        f"*Report time: {now.isoformat()}*",
    ])

    report = "\n".join(lines)
    filepath = save_report(report, "daily_report")
    log.info(f"✅ Daily report generated! Saved to {filepath}")

    return report


def generate_moltbook_post(analysis: dict, sentiment: dict) -> tuple[str, str]:
    """Generate an engaging post for Moltbook with clean formatting."""
    now = datetime.now()
    keywords = analysis.get("keywords", [])[:5]
    pcts = sentiment.get("percentages", {})
    patterns = analysis.get("agent_patterns", {})
    submolts = analysis.get("submolt_activity", [])[:3]

    # Dynamic title
    title = _pick_title(now)

    # Build content — clean formatting
    kw_list = ", ".join(kw["keyword"] for kw in keywords)

    pos = pcts.get('positive', 0)
    neu = pcts.get('neutral', 0)
    neg = pcts.get('negative', 0)

    content = f"Today's Top Topics: {kw_list}\n\n"
    content += f"Sentiment: {_sentiment_emoji(pos)} {pos}% positive | {neu}% neutral | {neg}% negative\n\n"
    content += (
        f"Unique Agents Analyzed: {patterns.get('unique_agents', '?')}\n"
        f"Posts Analyzed: {analysis.get('total_unique_posts', '?')}\n\n"
    )

    # Active submolts
    if submolts:
        sm_list = ", ".join(f"m/{s['submolt']} ({s['post_count']})" for s in submolts)
        content += f"Active Submolts: {sm_list}\n\n"

    # Top agents
    top_agents = patterns.get("top_posters", [])[:3]
    if top_agents:
        agent_list = ", ".join(f"@{a['name']} ({a['posts']})" for a in top_agents)
        content += f"Top Agents: {agent_list}\n\n"

    # Rising trends
    changes = analysis.get("trend_changes", [])
    rising = [c for c in changes if "rising" in c["trend"]][:3]
    if rising:
        content += "Rising Trends: "
        content += " ".join(f"📈 {r['keyword']} (+{r['change_pct']}%)" for r in rising)
        content += "\n\n"

    # Falling trends
    falling = [c for c in changes if "falling" in c["trend"]][:2]
    if falling:
        content += "Cooling Down: "
        content += " ".join(f"📉 {f['keyword']} ({f['change_pct']}%)" for f in falling)
        content += "\n\n"

    # Data-driven insight
    insight = _generate_insight(analysis, sentiment)
    if insight:
        content += f"💡 {insight}\n\n"

    content += "---\n"
    content += "*Generated by MoltBridge Agent — bridging Moltbook intelligence to the agent ecosystem.*"

    return title, content


def _generate_insight(analysis: dict, sentiment: dict) -> str:
    """Generate a brief data-driven insight."""
    pcts = sentiment.get("percentages", {})
    changes = analysis.get("trend_changes", [])
    patterns = analysis.get("agent_patterns", {})

    insights = []

    neg = pcts.get("negative", 0)
    pos = pcts.get("positive", 0)
    if neg > 20:
        insights.append(f"Negative sentiment is elevated at {neg}% — worth watching what's driving agent concerns.")
    elif pos > 25:
        insights.append(f"Positive vibes dominate at {pos}% — the agent ecosystem is feeling optimistic today.")
    elif pcts.get("neutral", 0) > 80:
        insights.append("Heavy neutral sentiment suggests agents are in information-sharing mode rather than opinion mode.")

    rising = [c for c in changes if "rising" in c["trend"]]
    if rising and rising[0]["change_pct"] > 50:
        insights.append(f"'{rising[0]['keyword']}' is surging with +{rising[0]['change_pct']}% growth — emerging hot topic.")

    one_timers = patterns.get("one_time_posters", 0)
    total = patterns.get("unique_agents", 1)
    if total > 0 and one_timers / total > 0.7:
        insights.append(f"{round(one_timers/total*100)}% of agents posted only once — high churn or lots of newcomers.")

    return insights[0] if insights else ""
